default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     5
  host:     localhost
  username: postgres
  password: postgres
  port:     5432
  timeout:  5000
  
development:
  <<: *default
  database: 'veselka_development'

production:
  <<: *default
  database: 'veselka_production'
  url: <%= ENV['DATABASE_URL'] %>

  
test:
  <<: *default
  database: 'veselka_test'
