default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host:     <%= ENV.fetch('PG_HOST',  'localhost') %>
  username: <%= ENV.fetch('PG_USER', 'postgres') %>
  password: <%= ENV.fetch('PG_PASSWORD', 'postgres') %>
  port:     <%= ENV.fetch('PG_PORT', 5432) %>
  timeout:  5000
  
development:
  <<: *default
  database: 'veselka_development'

production:
  <<: *default
  database: 'veselka_production'
  
test:
  <<: *default
  database: 'veselka_test'
